// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package server

import (
	"context"

	"jason-forum/apps/like/rpc/internal/logic"
	"jason-forum/apps/like/rpc/internal/svc"
	"jason-forum/apps/like/rpc/pb"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) Thumbup(ctx context.Context, in *pb.ThumbupRequest) (*pb.ThumbupResponse, error) {
	l := logic.NewThumbupLogic(ctx, s.svcCtx)
	return l.Thumbup(in)
}

func (s *LikeServer) IsThumbup(ctx context.Context, in *pb.IsThumbupRequest) (*pb.IsThumbupResponse, error) {
	l := logic.NewIsThumbupLogic(ctx, s.svcCtx)
	return l.IsThumbup(in)
}
